blog/urls.py
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity
from django.urls import path

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),

]

catalog/urls.py
from catalog.apps import CatalogConfig
from catalog.views import contact_inf, HomeListView, ProductListView, ProductDetailView, \
    ProductCreateView, ProductUpdateView
from django.urls import path

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('contacts/', contact_inf, name='contacts'),
    path('product/', ProductListView.as_view(), name='product'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='products_update'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),

]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    category_name = models.CharField(max_length=250, verbose_name='Наименование')
    category_description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    photo = models.ImageField(upload_to='online_store/', verbose_name='Превью', **NULLABLE)
    # category = models.CharField(max_length=150, verbose_name='Категория')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку', **NULLABLE)
    creation_date = models.DateField(verbose_name='Дата создания', **NULLABLE)
    last_modified_date = models.DateField(verbose_name='Дата последнего изменения', **NULLABLE)

    product_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                      verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.name} из категории "{self.category}"'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('name',)

catalog/forms.py
from django import forms

from catalog.models import Product


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'category', 'creation_date', 'last_modified_date', 'product_owner', 'price')

catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from catalog.forms import ProductForm
from catalog.models import Product


class HomeListView(ListView):
    model = Product
    template_name = 'catalog/home.html'
    extra_context = {'title': 'Homepage', }

    def get_queryset(self):
        return Product.objects.all()[:3]


def contact_inf(request):
    context = {
        'title': 'Contacts',
    }
    return render(request, 'catalog/contact_inf.html', context)


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product.html'
    extra_context = {'title': 'All categories products', }


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product')


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product')

catalog/templates/catalog/includes/inc_menu.html
<div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4 class="text-white">About</h4>
                <p class="text-muted">Add some information about the album below, the author, or any other
                    background context. Make it a few sentences long so folks can pick up some informative tidbits.
                    Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4 class="text-white">Меню</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'catalog:home' %}" class="text-white">Главная</a></li>
                    <li><a href="{% url 'catalog:product' %}" class="text-white">Все продукты</a></li>
                    <li><a href="{% url 'blog:list' %}" class="text-white">Блог</a></li>
                    <li><a href="{% url 'catalog:contacts' %}" class="text-white">Контакты</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                    <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                    {% else %}
                    <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                    <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

catalog/templates/catalog/includes/inc_product.html
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <h5 class="card-title">{{ object.name|title }}</h5>
            <p class="card-text">{{ object.description }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'catalog:product_detail' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">View</a>
                </div>
                {% if object.price %}
                <small class="text-muted">{{ object.price }} р.</small>
                {% else %}
                <small class="text-muted">Цена не указана</small>
                {% endif %}
            </div>
        </div>
        <div class="card-footer">
            <a class="btn btn-link" href="{% url 'catalog:products_update' object.pk %}">Изменить</a>
        </div>
    </div>
</div>